{{- if .Values.roles }}
{{- range .Values.roles }}
{{- if .roleBinding }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "chart.name" $ }}-{{ .name }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ $.Values.serviceAccount.name | default $.Values.default.serviceAccountName }}
  namespace: {{ $.Release.Namespace }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "chart.name" $ }}-{{ .name }}
  apiGroup: ""
---
{{- end }}
{{- end }}
{{- end }}