{{- if and .Values.secretManager.enabled (eq .Values.secretManager.type "external-secrets.io") .Values.secretManager.secretStore  -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  provider:
    # Only include this block if the provider is awsSecretsManager
    {{- if eq .Values.secretManager.secretStore.provider "awsSecretsManager" }}
    aws:
      service: SecretsManager
      region: {{ .Values.secretManager.secretStore.region | default "us-east-1" }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.secretManager.secretStore.authSecret }}
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: {{ .Values.secretManager.secretStore.authSecret }}
            key: AWS_SECRET_ACCESS_KEY
    {{- end -}}
{{- end }}