{{- if and .Values.clusterSecretStore (eq .Values.clusterSecretStore.enabled true) -}}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    ## Add this annotation to disable controller warning events for unmaintained stores
    external-secrets.io/disable-maintenance-checks: "true"
spec:
  provider:
    # Only include this block if the provider is awsSecretsManager
    {{- if (index .Values.clusterSecretStore.provider "aws") }}
    aws:
      service: SecretsManager
      region: {{ .Values.clusterSecretStore.provider.aws.region | default "us-east-1" }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: {{ $.Release.Namespace }}
            name: {{ .Values.clusterSecretStore.provider.aws.authSecret }}
            key: AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            namespace: {{ $.Release.Namespace }}
            name: {{ .Values.clusterSecretStore.provider.aws.authSecret }}
            key: AWS_SECRET_ACCESS_KEY
    {{- end -}}
{{- end }}