{{- if and .Values.clusterSecretStore (eq .Values.clusterSecretStore.enabled true) -}}
{{- range .Values.clusterSecretStore.secrets -}}
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ .name | lower | replace "/" "-" }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  externalSecretName: {{ .name | lower | replace "/" "-" }}
  namespaceSelectors:
    {{- toYaml .namespaceSelectors | nindent 4 }}
  refreshTime: {{ .refreshTime | default "1m" }}
  externalSecretSpec:
    refreshInterval: {{ .refreshInterval | default "24h" }}
    secretStoreRef:
      name: {{ include "chart.fullname" $ }}
      kind: ClusterSecretStore
    target:
      name: {{ .name | lower | replace "/" "-" }}
      creationPolicy: Owner
      {{- if eq .format "json" }}
      template:
        engineVersion: v2
        templateFrom:
        - target: Data
          literal: |-
            "token": {{ "{{ . | toJson | quote }}" }}
      {{- end }}
    dataFrom:
    - extract:
        key: {{ .name }}
---
{{- end -}}
{{- end -}}