{{- if and .Values.secretManager.enabled (eq .Values.secretManager.type "external-secrets.io")  -}}
{{- range .Values.secretManager.secrets -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "chart.fullname" $ }}-{{ .name | lower | replace "/" "-" }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ .refreshInterval | default "24h" }}
  secretStoreRef:
    name: {{ include "chart.fullname" $ }}
    kind: SecretStore
  target:
    name: {{ .name | lower | replace "/" "-" }}
    creationPolicy: Owner
    {{- if eq .format "json" }}
    template:
      engineVersion: v2
      templateFrom:
      - target: Data
        literal: |-
          "token": {{ "{{ . | toJson | quote }}" }}
    {{- end }}
  dataFrom:
  - extract:
      key: {{ .name }}
---
{{- end -}}
{{- end -}}